version: "3"
name: atavism-server
services:
  atavism-module:
    build:
      context: ./../../..
      dockerfile: docker/images/base/Dockerfile
      target: production
    depends_on:
      - mysql-master
      - mysql-admin
      - mysql-atavism
      - mysql-world
    restart: always
    links:
      - mysql-master
      - mysql-admin
      - mysql-atavism
      - mysql-world

  atavism-master:
    build:
      context: ./../../..
      dockerfile: docker/images/base/Dockerfile
      target: production
      args:
        - IMAGE_NAME=master
    restart: always
    ports:
      - 9005:9005/tcp
      - 9010:9010/udp
    depends_on:
      - mysql-master
    links:
      - mysql-master
