package atavism.agis.plugins;

import atavism.msgsys.Message;
import atavism.msgsys.MessageTypeFilter;
import atavism.server.engine.Engine;
import atavism.server.engine.EnginePlugin;
import atavism.server.engine.Hook;
import atavism.server.engine.Namespace;
import atavism.server.engine.OID;
import atavism.server.objects.Entity;
import atavism.server.util.Logger;
import atavism.server.plugins.WorldManagerClient.ExtensionMessage;

public class SuperheroPlugin extends EnginePlugin {
	public SuperheroPlugin() {
		super("SuperheroPlugin");
		setPluginType("SuperheroPlugin");
	}

	public String getName() {
		return "Superhero";
	}

	public void onActivate() {
		log.info("SuperheroPlugin activate");
		super.onActivate();
		this.registerHooks();
	}

	private static final Logger log = new Logger("SuperheroPlugin");

	public void registerHooks() {

		// Generated by AtavismServerDocker generator
		this.registerShootLaserFromEyesHook();

	}




	/**
		* Register ShootLaserFromEyesHook
		* Generated by AtavismDockerServer generator
		*/
	protected void registerShootLaserFromEyesHook()
	{
		getHookManager().addHook(SuperheroClient.MSG_TYPE_SUPERHERO_SHOOT_LASER_FROM_EYES,
				new ShootLaserFromEyesHook());
		MessageTypeFilter filter = new MessageTypeFilter();
		filter.addType(SuperheroClient.MSG_TYPE_SUPERHERO_SHOOT_LASER_FROM_EYES);
		Engine.getAgent().createSubscription(filter, this);
	}
	
	/**
		* ShootLaserFromEyesHook
		* Generated by AtavismServerDocker generator
		*/
	class ShootLaserFromEyesHook implements Hook {
		public boolean processMessage(Message msg, int flags) {
			log.info("ShootLaserFromEyes triggered!");
			ExtensionMessage gmMsg = (ExtensionMessage) msg;

			return true;
		}
	}

}
