package atavism.agis.plugins;

import java.io.IOException;
import java.io.Serializable;

import atavism.server.plugins.WorldManagerClient.ExtensionMessage;
import atavism.msgsys.MessageType;
import atavism.server.util.*;
import atavism.server.engine.*;
import atavism.server.messages.*;

public class SuperheroClient {
	protected SuperheroClient() {
	}

		/**
		* ShootLaserFromEyes Class
		* Generated by AtavismServerDocker
		*/
		public static class ShootLaserFromEyesMessage extends ExtensionMessage {
			private static final long serialVersionUID = 1L;

			public ShootLaserFromEyesMessage() {

				super();
			}

			public ShootLaserFromEyesMessage(OID oid) {
				super(oid);
				setMsgType(MSG_TYPE_SUPERHERO_SHOOT_LASER_FROM_EYES);
				Log.info("ShootLaserFromEyes created!");
			}
		}

		/**
		* ShootLaserFromEyes constant
		* Generated by AtavismServerDocker
		*/
		public static final MessageType MSG_TYPE_SUPERHERO_SHOOT_LASER_FROM_EYES = MessageType
				.intern("superhero.SHOOT_LASER_FROM_EYES");
}
