version: "3"
name: atavism-server
include:
  - ../common/resources.yml
  - master.yml
services:
  world:
    extends:
      file: module.yml
      service: atavism-module-development
    volumes:
      - ../../images/world/start.sh:/start.sh
    ports:
      - 5042:5042/tcp
      - 5052:5052/udp
      - 5566:5566/tcp
